---
title: Trait Matching and Spectrum
output: pdf_document
fontsize: 10pt
---

```{r packs, results = 'hide'}
require(doMC)
registerDoMC(cores = 3)
require(plotrix)
require(plyr)
require(dplyr)
require(magrittr)
require(ggplot2)
require(RColorBrewer)
```

Load empirical networks:

```{r load_empirical}
binary.files <- dir('data/empirical_networks/binary/')
binary.networks <- list()

for(i in 1:length(binary.files))
    binary.networks [[i]] <-
        as.matrix(read.table(paste0('data/empirical_networks/binary/', binary.files [i])))

names(binary.networks) <- gsub('_bin.txt', '', binary.files)
```

Also, load function:

```{r source_script}
source('functions/twoSitesVectorMatch.R')
source('functions/assembleQ.R')
```

We are going to test a lot of scenarios here:

```{r choose_network}
net <- binary.networks [[61]] # Olesen 2002 (10 x 12)
color2D.matplot(net)
```

```{r sim1, cache = TRUE}
## scenarios to be tested
flow <- seq(0.01, 0.1, by = 0.01)
hotA <- seq(0.1, 1, by = 0.1)
hotB <- hotA

## other pars
temp <- 0.1
h <- 0.1

thA <- rnorm(sum(dim(net)), 20, 4)
thB <- rnorm(sum(dim(net)), 40, 4)

### all combinations of simulation values
par.table <- as.matrix(expand.grid(flow, hotA, hotB))

dimnames(par.table) <- NULL

## one hundred simulations per combination of g, mA, mB
## massive set of lists within lists
sim.spectral <- alply(1:100, 1, function(i)
    {
        iA <- runif(sum(dim(net)), 10, 50)
        iB <- runif(sum(dim(net)), 10, 50)

        alply(1:nrow(par.table), 1, function(j)
            twoSitesVectorMatch(net, par.table[j, 1], h, temp,
                                thA, thB, par.table[j, 2], par.table[j, 3], iA, iB), 
            .parallel = TRUE)
    })
```
